# TODO add requests & limits
# TODO increase replicas
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tmp
  labels:
    app: tmp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tmp
  template:
    metadata:
      labels:
        app: tmp
    spec:
      containers:
      - image: fnsdev/tmp:latest
        name: tmp
        env:
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: environment
              key: django_secret_key
        - name: DJANGO_DB_NAME
          valueFrom:
            secretKeyRef:
              name: environment
              key: django_db_name
        - name: DJANGO_DB_USER
          valueFrom:
            secretKeyRef:
              name: environment
              key: django_db_user
        - name: DJANGO_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: environment
              key: django_db_password
        - name: DJANGO_DB_HOST
          valueFrom:
            secretKeyRef:
              name: environment
              key: django_db_host
        - name: DJANGO_DB_PORT
          valueFrom:
            secretKeyRef:
              name: environment
              key: django_db_port
        - name: EMAIL_HOST_USER
          valueFrom:
            secretKeyRef:
              name: environment
              key: email_host_user
        - name: EMAIL_HOST_PASSWORD
          valueFrom:
            secretKeyRef:
              name: environment
              key: email_host_password
        - name: GS_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: environment
              key: gs_bucket_name
        - name: GS_CREDENTIALS
          valueFrom:
            secretKeyRef:
              name: environment
              key: gs_credentials
        - name: GS_PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: environment
              key: gs_project_id
        - name: URL
          valueFrom:
            secretKeyRef:
              name: environment
              key: url
        - name: GITHUB_INTEGRATION_SERVICE_URL
          valueFrom:
           secretKeyRef:
             name: environment
             key: github_integration_service_url
        - name: GITHUB_CLIENT_ID
          valueFrom:
           secretKeyRef:
             name: environment
             key: github_client_id
        - name: GITHUB_CLIENT_SECRET
          valueFrom:
           secretKeyRef:
             name: environment
             key: github_client_secret
        ports:
        - containerPort: 80
          name: tmp
