apiVersion: batch/v1
kind: Job
metadata:
  name: run-tests
spec:
  template:
    spec:
      containers:
      - name: tmp-tests
        image: fnsdev/tmp:gitrello
        imagePullPolicy: Always
        env:
          - name: DJANGO_DB_NAME
            valueFrom:
              secretKeyRef:
                name: gitrello-environment
                key: django_db_name
          - name: DJANGO_DB_USER
            valueFrom:
              secretKeyRef:
                name: gitrello-environment
                key: django_db_user
          - name: DJANGO_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: gitrello-environment
                key: django_db_password
          - name: DJANGO_DB_HOST
            valueFrom:
              secretKeyRef:
                name: gitrello-environment
                key: django_db_host
          - name: DJANGO_DB_PORT
            valueFrom:
              secretKeyRef:
                name: gitrello-environment
                key: django_db_port
      restartPolicy: Never
  backoffLimit: 1
  activeDeadlineSeconds: 120
