statefulset:
  resources:
    limits:
      cpu: "0.4"
      memory: "0.8Gi"
    requests:
      cpu: "0.4"
      memory: "0.8Gi"
storage:
  persistentVolume:
    storageClass: "cockroachdb"
    size: 2Gi
service:
  public:
    type: LoadBalancer
    annotations:
      metallb.universe.tf/allow-shared-ip: gitrello
conf:
  cache: "0.2Gi"
  max-sql-memory: "0.2Gi"
tls:
  enabled: true
