apiVersion: v1
kind: PersistentVolume
metadata:
  name: cockroachdb-pv-1
  labels:
    app: cockroachdb
spec:
  storageClassName: cockroachdb
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/cockroachdb-1/data"
