statefulset:
  resources:
    limits:
      cpu: "0.4"
      memory: "800Mi"
    requests:
      cpu: "0.4"
      memory: "800Mi"
storage:
  persistentVolume:
    storageClass: "cockroachdb"
    size: 2Gi
service:
  public:
    type: LoadBalancer
    annotations:
      metallb.universe.tf/allow-shared-ip: gitrello
conf:
  cache: "200Mi"
  max-sql-memory: "200Mi"
tls:
  enabled: true
