# Generated by Django 3.0.3 on 2020-03-14 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='board',
            unique_together={('name', 'organization')},
        ),
    ]
