# Generated by Django 3.0.4 on 2020-05-11 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmembership',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_memberships', to='boards.Board'),
        ),
        migrations.AlterField(
            model_name='boardmembership',
            name='organization_membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_memberships', to='organizations.OrganizationMembership'),
        ),
    ]
