# Generated by Django 3.0.8 on 2020-08-18 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_alter__board_membership'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ('-added_at',)},
        ),
    ]
