apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitrello-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
        - gitrello.me
        - www.gitrello.me
      secretName: tls
  rules:
    - host: gitrello.me
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: gitrello
              port:
                number: 80
    - host: www.gitrello.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gitrello
                port:
                  number: 80
