apiVersion: v1
kind: Service
metadata:
  name: test-database-service
  namespace: ci
  labels:
    app: gitrello
    env: test
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: gitrello
    env: test
