apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-database
  namespace: ci
spec:
  template:
    spec:
      containers:
      - name: gitrello-migrate-database
        image: fnsdev/gitrello:current
        imagePullPolicy: Always
        command: ["sh", "-c", "python manage.py migrate --noinput --settings=gitrello.settings_prod"]
        env:
          - name: DJANGO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: environment
                key: django_secret_key
          - name: DJANGO_DB_NAMEa
            valueFrom:
              secretKeyRef:
                name: environment
                key: django_db_name
          - name: DJANGO_DB_USER
            valueFrom:
              secretKeyRef:
                name: environment
                key: django_db_user
          - name: DJANGO_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: environment
                key: django_db_password
          - name: DJANGO_DB_HOST
            valueFrom:
              secretKeyRef:
                name: environment
                key: django_db_host
          - name: DJANGO_DB_PORT
            valueFrom:
              secretKeyRef:
                name: environment
                key: django_db_port
          - name: EMAIL_HOST_USER
            valueFrom:
              secretKeyRef:
                name: environment
                key: email_host_user
          - name: EMAIL_HOST_PASSWORD
            valueFrom:
              secretKeyRef:
                name: environment
                key: email_host_password
          - name: GS_BUCKET_NAME
            valueFrom:
              secretKeyRef:
                name: environment
                key: gs_bucket_name
          - name: GS_CREDENTIALS
            valueFrom:
              secretKeyRef:
                name: environment
                key: gs_credentials
          - name: GS_PROJECT_ID
            valueFrom:
              secretKeyRef:
                name: environment
                key: gs_project_id
      restartPolicy: Never
  backoffLimit: 1
  activeDeadlineSeconds: 120
