# Generated by Django 3.0.4 on 2020-05-24 13:40

from django.db import migrations, models

SET_PRIORITIES_SQL = """
    with tickets_with_priorities as (
        select
            id,
            row_number () over (
                partition by category_id
                order by added_at
            ) - 1 as priority
        from tickets_ticket
        order by category_id, added_at 
    )
    update tickets_ticket
    set
        priority = twp.priority
    from tickets_with_priorities twp
    where
        tickets_ticket.id = twp.id;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter__ticketassignment__alter__ticket__alter__assignee'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunSQL(SET_PRIORITIES_SQL, migrations.RunSQL.noop),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.IntegerField(),
        ),
    ]
