# Generated by Django 3.0.4 on 2020-05-25 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter__ticket__add__priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['priority']},
        ),
    ]
