# Generated by Django 3.0.8 on 2020-08-18 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_create__comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-added_at',)},
        ),
    ]
