# Generated by Django 3.1.2 on 2020-11-15 11:44

from django.db import migrations, models

SET_PRIORITIES_SQL = """
    with categories_with_priorities as (
        select
            id,
            row_number () over (
                partition by board_id
                order by added_at
            ) - 1 as priority
        from tickets_category
        order by board_id, added_at 
    )
    update tickets_category
    set
        priority = cwp.priority
    from categories_with_priorities cwp
    where
        tickets_category.id = cwp.id;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_alter__comment__alter__meta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['priority']},
        ),
        migrations.AddField(
            model_name='category',
            name='priority',
            field=models.IntegerField(null=True),
        ),
        migrations.RunSQL(SET_PRIORITIES_SQL, migrations.RunSQL.noop),
        migrations.AlterField(
            model_name='category',
            name='priority',
            field=models.IntegerField(),
        ),
    ]
